# Generated by Django 6.0.5 on 2026-06-09 11:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Identify this in code (e.g., 'header' or 'footer').", unique=True)),
                ('menu_items', wagtail.fields.StreamField([('menu_items', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "The Main Menu Item (e.g., 'Members')"}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 4), ('link_page', 1), ('link_url', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('link_url', 2), ('description', 3), ('sub_links', 6)]], {})})),
            ],
        ),
    ]
