# Generated by Django 6.0.5 on 2026-06-09 12:09

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.fields.StreamField([('page_link', 7), ('external_link', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 3), ('link_url', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('page', 1), ('description', 2), ('sub_links', 6)]], {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 8), ('description', 2), ('sub_links', 6)]], {})}),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text="Menu Name (e.g., 'main nav' or 'sidebar nav').", max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(help_text="Slug used by frontend to fetch menu (e.g., 'main-nav' or 'footer-nav').", unique=True),
        ),
    ]
