# Generated by Django 6.0.5 on 2026-06-09 12:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_menu_items_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.fields.StreamField([('page_link', 2), ('external_link', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.URLBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 3)]], {})}),
        ),
    ]
