# Generated by Django 6.0.5 on 2026-06-09 13:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.fields.StreamField([('page_link', 2), ('external_link', 4), ('links_group', 6), ('dropdown', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.URLBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 3)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('page_link', 2), ('external_link', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 5)]], {}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional — makes the dropdown title a clickable link.', 'required': False}), 8: ('wagtail.blocks.StreamBlock', [[('page_link', 2), ('external_link', 4), ('links_group', 6)]], {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('page', 7), ('items', 8)]], {})}),
        ),
    ]
